### ISSUE TITLE
Command class \"Davispeixoto\\TestGenerator\\Commands\\TestsGeneratorCommand\" is not correctly initialized. You probably forgot to call the parent constructor.

### ISSUE THREAD

**Issue by ninobaldo** [davispeixoto/Laravel-4-Test-Generator#1]
This happens in version 4.1 laravel.

$ artisan
Command class \"Davispeixoto\TestGenerator\Commands\TestsGeneratorCommand\" is not correctly initialized. You probably forgot to call the parent constructor.

resolve #2

**Comment by ghost** [comment]
I'm getting this error, what was the fix

**Comment by jhoanborges** [comment]
+1
