### ISSUE TITLE
Composer not loading

### ISSUE THREAD

**Issue by shivergard** [davispeixoto/Laravel-4-Test-Generator#5]
```
"require": {
    "laravel/framework": "4.*",
    "davispeixoto/laravel-test-generator": "1.0.*"
},
```

done "composer update" , but doesn't seams to be loaded...

**Comment by shivergard** [comment]
???

**Comment by davispeixoto** [comment]
What do you mean by "but doesn't seams to be loaded..."?

Did you try to generate any tests and got an error?

**Comment by shivergard** [comment]
It did not load in vendor code. I've attached Provider and it fall on fatal error , that provider not found. Redone it to blank Laravel project for couple of times.

**Comment by shivergard** [comment]
php artisan 
PHP Fatal error:  Class 'Davispeixoto\Testingtool\TestingtoolServiceProvider' not found in /opt/[PROJECTPATH]/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Davispeixoto\\Testingtool\\TestingtoolServiceProvider' not found","file":"\/opt\/[PROJECTPATH]\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}

**Comment by shivergard** [comment]
I switched to "davispeixoto/laravel-test-generator": "dev-master", for getting this

**Comment by davispeixoto** [comment]
I'm working on this. Thx for the information provided so far.

**Comment by davispeixoto** [comment]
Fixed. I've updated the documentation.

The proper ServiceProvider actually is "Davispeixoto\TestGenerator\TestGeneratorServiceProvider"

**Comment by shivergard** [comment]
Thank you ))
